### ISSUE TITLE
Sorry, the page you are looking for could not be found.

### ISSUE THREAD

**Issue by mouad-mahfoud** [anasmorahhib/deploy-Laravel-5-project-to-a-shared-hosting#1]
after I include the files it gives me this Sorry, the page you are looking for could not be found.

**Comment by anasmorahhib** [comment]
give me the structure of your files.

**Comment by mouad-mahfoud** [comment]
![capture](https://user-images.githubusercontent.com/17494267/42464207-394d42d8-83a0-11e8-91a3-05bd472e7b1f.PNG)
